export const EVENT_LLM_DOMAIN = 'EVENT_LLM_DOMAIN';
export const SELECTED_EVENT_NAME = 'SELECTED_EVENT_NAME';
export const SELECTED_SESSION = 'SELECTED_SESSION';
export const IS_PROJECT_ON_PHYSICAL_SCREEN = 'IS_PROJECT_ON_PHYSICAL_SCREEN';
