service: elsa-at-event-admin-app
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ca-central-1"}
  stackTags:
    REPOSITORY: "elsa-at-event-mic-app"
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - "s3:*"
        - "s3:PutBucketPublicAccessBlock"
        - "s3:DeletePublicAccessBlock"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:PutObjectTagging"
        - "cloudformation:*"
      Resource: "*"

resources:
  Resources:
    OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: !Sub Admin app assets
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-${self:service}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration: 
          BlockPublicAcls: FALSE
          BlockPublicPolicy: FALSE
          IgnorePublicAcls: FALSE
          RestrictPublicBuckets: FALSE  
    MyRoute53RecordGroupSet:
        DependsOn: OriginAccessIdentity
        Type: AWS::Route53::RecordSetGroup
        Properties:
          HostedZoneId: ${env:HOSTED_ZONE_ID}
          RecordSets:
            - Name: ${env:DOMAIN_NAME}
              Type: A
              AliasTarget:
                DNSName: !GetAtt ApiDistribution.DomainName 
                HostedZoneId: Z2FDTNDATAQYW2 

  extensions:
    WebAppS3BucketPolicy:
      Properties:
        Bucket: !Ref WebAppS3Bucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Join
                - ""
                - - !GetAtt WebAppS3Bucket.Arn
                  - "/*"
              Principal:
                CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
                AWS: "*"

    ApiDistribution:
      Properties:
        DistributionConfig:
          Origins:
            - Id: WebApp
              DomainName: !GetAtt WebAppS3Bucket.DomainName
              S3OriginConfig:
                OriginAccessIdentity: !Join
                  - /
                  - - origin-access-identity
                    - cloudfront
                    - !Ref OriginAccessIdentity
          Enabled: true
          HttpVersion: http2
          Comment: Serverless Managed ${self:provider.stage}-${self:service}
          Aliases:
            - ${env:DOMAIN_NAME}
          PriceClass: PriceClass_All
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: false
            TargetOriginId: WebApp
            ForwardedValues:
              QueryString: "false"
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            AcmCertificateArn: ${env:ACM_CERTIFICATE_ARN}
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          CustomErrorResponses:
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html


plugins:
  - fullstack-serverless 
custom:
  fullstack:
    bucketName: ${self:service}
    distributionFolder: /dist/Angularproject
    indexDocument: index.html
    errorDocument: index.html
    compressWebContent: true
    clientCommand: ng build --configuration=${env:deployment}
    clientSrcPath: ./
    noConfirm: true
    invalidationPaths: /* 
    spa:
      errorConfigurations:
        - errorCode: 404
          responseCode: 200
          responsePagePath: /index.html

package:
  individually: true
  
  exclude:
    - node_modules/**
    - venv/**
    - tsconfig.spec.json
    - tsconfig.json
    - README.md
    - create_project.txt
    - angular.json 
    - package-lock.json
    - package.json
