export const environment = {
  production: false,
  getTranscriberPreSignedUrl: '',
  getContentVersionsUrl: '',
  genarateContentUrl: '',
  getVersionContentUrl: '',
  saveEditedVersionContentUrl: '',
  generateContentPDFUrl: '',
  getPreSignedPDFUrl: '',
  prompt_mangement_base_url: '',
  putTranscript: '',
  postData: '',
  getEventDetails: '',
  postCurrentSessionId: '',
  USER_POOL_WEB_CLIENT_ID: '',
  // USER_POOL_WEB_CLIENT_ID:'3ppt7i0sou74e5bks8mc5ph350',
  AUTH_API_END_POINT: '',
  REQUEST_ACCESS_API: '',
  REQUEST_ACCESS_API_KEY: '',
  USER_POOL_ID: '',
  // USER_POOL_ID:'ca-central-1_V9KhUwxNc',
  //  cognitoUserPoolId:'ca-central-1_V9KhUwxNc',
  // cognitoAppClientId:'3ppt7i0sou74e5bks8mc5ph350',
  eventName: '',
  eventDomain: '',
};
