export const environment = {
  production: false,
  getTranscriberPreSignedUrl: '',
  putTranscript: '',
  postData: '',
  getEventDetails: '',
  getEventConfig: '',
  postCurrentSessionId: '',
  USER_POOL_WEB_CLIENT_ID: '',
  AUTH_API_END_POINT: '',
  REQUEST_ACCESS_API: '',
  REQUEST_ACCESS_API_KEY: '',
  USER_POOL_ID: '',
  X_API_KEY: '',
};
